FROM redis:latest

# Définir le répertoire de travail
WORKDIR /data

# Copier un fichier de configuration Redis personnalisé (optionnel)
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Exposer le port Redis
EXPOSE 6379

# Commande de démarrage de Redis
CMD ["redis-server", "--appendonly", "yes"]
