FROM python:3.12-slim


RUN mkdir -p /var/log/bot
RUN mkdir -p /var/www/html
RUN mkdir -p /opt/dependencies/.venv

RUN chown -R www-data:www-data /var/www/html
RUN chown -R www-data:www-data /opt/dependencies/
RUN chown -R www-data:www-data /var/log/bot

RUN mkdir -p /usr/share/nginx/
RUN ln -s /var/www/html /usr/share/nginx/html

WORKDIR /opt/dependencies/.venv
# RUN mkdir /var/log/bot
USER www-data
# Create a virtual environment in /opt/dependencies
RUN python -m venv /opt/dependencies/.venv

ENV PATH="/opt/dependencies/.venv/bin:$PATH"
COPY docker/requirements.txt /opt/dependencies/requirements.txt

RUN /opt/dependencies/.venv/bin/pip install --no-cache-dir -r /opt/dependencies/requirements.txt

# Copy the source code into /app/html

WORKDIR /var/www/html

COPY src .

USER root
RUN chown -R www-data:www-data /var/www/html

USER www-data

EXPOSE 8080

# Run the application
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8080"]