FROM python:3.12-slim

# Create all required directories first
RUN mkdir -p /var/log/bot /var/www/html /opt/dependencies/.venv /var/www/html/bot/variables /usr/share/nginx/

# Create symbolic link
RUN ln -s /var/www/html /usr/share/nginx/html

# Set very permissive permissions (for debugging purposes)
RUN chmod -R 777 /var/www/html /opt/dependencies/ /var/log/bot

WORKDIR /opt/dependencies/.venv

# Create a virtual environment
RUN python -m venv /opt/dependencies/.venv

ENV PATH="/opt/dependencies/.venv/bin:$PATH"
COPY docker/requirements.txt /opt/dependencies/requirements.txt

RUN /opt/dependencies/.venv/bin/pip install --no-cache-dir -r /opt/dependencies/requirements.txt

# Copy the source code
WORKDIR /var/www/html
COPY src .


EXPOSE 8080

# Run the application
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8080"]