services:
  fastapi-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: Bot
    volumes:
      - ../src:/usr/share/nginx/html:rw
    ports:
      - "8080:8080"
    env_file:
      - ../src/.env